[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.pyright]
include = ["text_editor", "tests"]
typeCheckingMode = "basic"
pythonVersion = "3.8"