[project]
name = "refactorbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.3.2",
    "huggingface-hub[hf-transfer]>=0.29.1",
]
