[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"

[tool.ruff]
line-length = 88
target-version = "py37"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = []

[tool.pyright]
include = ["vm_emulator"]
exclude = ["**/__pycache__"]
reportMissingImports = true
reportMissingTypeStubs = false