[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "file_system_analyzer"
version = "0.1.0"
description = "Compliance Data Discovery Analyzer for security auditing"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "pydantic>=2.0.0",
    "cryptography>=40.0.0",
    "xxhash>=3.0.0",
    "python-magic>=0.4.24",
    "pytz",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-json-report>=1.5.0",
    "ruff>=0.0.240",
    "pyright>=1.1.300",
]

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []

[tool.pyright]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.8"