[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "securetask"
version = "0.1.0"
description = "Command-line task management system for security professionals"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cryptography>=41.0.0",
    "pydantic>=2.0.0",
    "pycryptodome>=3.18.0",
    "python-jose>=3.3.0",
    "jinja2>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-benchmark>=4.0.0",
    "pytest-json-report>=1.5.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"