[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "writer_text_editor"
version = "0.1.0"
description = "A specialized text editor library for fiction writers"
readme = "README.md"
authors = [
    {name = "Elena", email = "elena@example.com"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "nltk",
    "textstat",
    "spacy",
    "pydantic",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-json-report",
    "ruff",
    "pyright",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.pyright]
include = ["src", "tests"]
pythonVersion = "3.8"