[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unified-text_editor"
version = "0.1.0"
description = "Unified libraries for text_editor with original package names preserved"
requires-python = ">=3.8"
dependencies = ["nltk", "textstat", "spacy", "pydantic"]

[project.optional-dependencies]
dev = ["pytest", "pytest-json-report", "ruff", "pyright"]

[tool.setuptools]
packages = ["common", "text_editor", "writer_text_editor"]

[tool.pytest]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.pyright]
include = ["text_editor", "tests"]
typeCheckingMode = "basic"
pythonVersion = "3.8"
