[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "secure_vm"
version = "0.1.0"
description = "A specialized virtual machine emulator for security research and education"
authors = [
    {name = "Dr. Chen", email = "example@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Security",
]

[project.optional-dependencies]
test = ["pytest", "pytest-json-report"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.pyright]
include = ["src", "tests"]
typeCheckingMode = "basic"